set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CXX_FLAGS "-m32")
set(VCPKG_C_FLAGS "-m32")
set(VCPKG_LINKER_FLAGS "-m32")

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
